package io.github.ulviar.mystem4j.gradle;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import org.gradle.api.DefaultTask;
import org.gradle.api.GradleException;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputFile;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;
import org.gradle.work.DisableCachingByDefault;

/**
 * Writes local runtime properties for a prepared MyStem executable.
 *
 * <p>The plugin registers this task as {@code mystemPrepareTestRuntime}, depending on
 * {@code mystemProbe}. Its UTF-8 properties file contains {@code mystem4j.executable}
 * (an absolute path) and {@code mystem4j.version}. The file is machine-local and should
 * not be packaged as a portable runtime configuration.
 *
 * <p>This task only writes the file. The plugin separately injects the executable
 * path into {@link org.gradle.api.tasks.testing.Test} processes when
 * {@link Mystem4jExtension#getConfigureTests()} is enabled; the runtime library does
 * not automatically load this properties file.
 */
@DisableCachingByDefault(because = "Writes local runtime properties that point at the prepared executable path.")
public abstract class MystemPrepareRuntimeTask extends DefaultTask {
    /**
     * Creates a Gradle-managed task whose properties are configured by the plugin or build script.
     */
    public MystemPrepareRuntimeTask() {}

    /**
     * Returns the native MyStem version to record.
     *
     * @return native version property
     */
    @Input
    public abstract Property<String> getVersion();

    /**
     * Returns the executable whose absolute path is recorded.
     * The plugin's task dependency probes it before this action runs.
     *
     * @return prepared executable input file
     */
    @InputFile
    @PathSensitive(PathSensitivity.NONE)
    public abstract RegularFileProperty getExecutableFile();

    /**
     * Returns the UTF-8 properties output, replacing any existing file.
     *
     * @return local runtime properties file
     */
    @OutputFile
    public abstract RegularFileProperty getPropertiesFile();

    /**
     * Writes the executable path and version, creating parent directories when needed.
     *
     * @throws GradleException if the properties file cannot be written
     */
    @TaskAction
    public void writeRuntimeProperties() {
        Path executable = getExecutableFile().get().getAsFile().toPath();
        Path propertiesFile = getPropertiesFile().get().getAsFile().toPath();
        Properties properties = new Properties();
        properties.setProperty(Mystem4jPlugin.EXECUTABLE_PROPERTY, executable.toAbsolutePath().toString());
        properties.setProperty("mystem4j.version", getVersion().get());

        try {
            Files.createDirectories(propertiesFile.getParent());
            try (Writer writer = Files.newBufferedWriter(propertiesFile, StandardCharsets.UTF_8)) {
                properties.store(writer, "Generated by mystemPrepareTestRuntime");
            }
            getLogger().lifecycle("Prepared MyStem test runtime properties: {}", propertiesFile);
        } catch (IOException error) {
            throw new GradleException("Failed to write MyStem runtime properties to " + propertiesFile, error);
        }
    }
}
