package io.github.ulviar.mystem4j.gradle;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import org.gradle.api.DefaultTask;
import org.gradle.api.GradleException;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputFile;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;
import org.gradle.work.DisableCachingByDefault;

@DisableCachingByDefault(because = "Writes local runtime properties that point at the prepared executable path.")
public abstract class MystemPrepareRuntimeTask extends DefaultTask {
    @Input
    public abstract Property<String> getVersion();

    @InputFile
    @PathSensitive(PathSensitivity.NONE)
    public abstract RegularFileProperty getExecutableFile();

    @OutputFile
    public abstract RegularFileProperty getPropertiesFile();

    @TaskAction
    public void writeRuntimeProperties() {
        Path executable = getExecutableFile().get().getAsFile().toPath();
        Path propertiesFile = getPropertiesFile().get().getAsFile().toPath();
        Properties properties = new Properties();
        properties.setProperty(Mystem4jPlugin.EXECUTABLE_PROPERTY, executable.toAbsolutePath().toString());
        properties.setProperty("mystem4j.version", getVersion().get());

        try {
            Files.createDirectories(propertiesFile.getParent());
            try (Writer writer = Files.newBufferedWriter(propertiesFile, StandardCharsets.UTF_8)) {
                properties.store(writer, "Generated by mystemPrepareTestRuntime");
            }
            getLogger().lifecycle("Prepared MyStem test runtime properties: {}", propertiesFile);
        } catch (IOException error) {
            throw new GradleException("Failed to write MyStem runtime properties to " + propertiesFile, error);
        }
    }
}
